Proofread Notification Endpoint section
openid/OpenID4VCI pull request #183
Opened 2023-12-29 23:15 UTC by selfissued

Correct issues identified while proofreading the Notification Endpoint section.

2023-12-30 12:23 UTC, peppelinux approved these changes

2024-01-05 23:38 UTC, bc-pi requested changes
One small (but I think important) change requested. Otherwise looks good.

2024-01-05 23:38 UTC, bc-pi commented on openid-4-verifiable-credential-issuance-1_0.md
> +If the Notification Request does not contain an Access Token or contains an invalid Access Token, the Notification Endpoint returns an Authorization Error Response, as defined in Section 3 of [@!RFC6
the "such as" here was intentional so as not to preclude `WWW-Authenticate` challenges with schemes other than `Bearer` like `DPoP` 

```suggestion
If the Notification Request does not contain an Access Token or contains an invalid Access Token, the Notification Endpoint returns an Authorization Error Response, such as defined in Section 3 of [@!RFC6750].
```

2024-01-06 00:41 UTC, bc-pi approved these changes

2024-01-08 22:26 UTC, tplooker approved these changes

2024-01-10 19:43 UTC, awoie approved these changes

2024-01-12 23:58 UTC, Sakurann requested changes

2024-01-12 23:58 UTC, Sakurann commented on openid-4-verifiable-credential-issuance-1_0.md
> +* `error`: REQUIRED. A name at the top level of the object, the value of which SHOULD be one of the following ASCII [@!USASCII] error codes:
```suggestion
* `error`: REQUIRED. The value of the `error` parameter SHOULD be one of the following ASCII [@!USASCII] error codes:
```
per PR #181.

2024-01-13 02:17 UTC, Sakurann approved these changes

2024-01-13 02:17 UTC, merged