Improve vc+sd-jwt metadata example
openid/OpenID4VCI pull request #195
Opened 2023-12-31 18:12 UTC by selfissued

This addresses some of the issues raised by @TakahikoKawasaki in #172.

2024-01-04 10:06 UTC, Sakurann approved these changes
looks ok. please make it clear in the issue, which on Taka's comments have been addressed and which have not, otherwise it will be harder to track later.

2024-01-04 10:07 UTC, Sakurann requested changes
per 18013-5, it is `age_over_NN`. please change from `age_65_or_over` to `age_over_65`

2024-01-04 13:57 UTC, paulbastian commented
`age_xx_or__over` claims are not in the IANA registry. Should they be prepended with something like an URI to make them public claims?

2024-01-05 01:23 UTC, selfissued commented
"Age over 65" means "Age > 65" - which is 66 or greater, in the normal English reading of the phrase.  It's an example.  I'd rather that the example read in a natural way, than have readers think "I know what they meant but that's not what they actually said."

To Paul's point about registering the claims, these are example claims for illustrative purposes only.

2024-01-05 01:30 UTC, Sakurann commented
I am afraid this is not an English question. 18013-5 already defined  "age_over_xx" which is used by the governments and other implementations and we should just use it. I am against introducing a new proprietary claim "age_xx_or_over".

2024-01-05 02:13 UTC, jogu commented
> "Age over 65" means "Age > 65" - which is 66 or greater, in the normal English reading of the phrase. It's an example. I'd rather that the example read in a natural way, than have readers think "I know what they meant but that's not what they actually said."

I think the interpretation does vary; at least in the United Kingdom it is common to say "you can drink alcohol once you're over 18", which means ">= 18", or perhaps more precisely "> 18.000000".

> To Paul's point about registering the claims, these are example claims for illustrative purposes only.

Unfortunately illustrative examples in specifications have a tendency to get copied and used in real life implementations. If we are not confident in the names or they are contentious etc then I suggest we just remove the "over xx years old" claims from the example here (and perhaps refer people to the actual SD JWT VC spec for more detailed examples).

2024-01-05 02:21 UTC, Sakurann commented
I don't understand why there is a controversy around using "age_over_nn" claim which is a relatively established claim in this space.

2024-01-06 02:08 UTC, selfissued commented on examples/credential_metadata_sd_jwt_vc.json
> +                "age_65_or_over": {}
```suggestion
                "is_over_18": {},
                "is_over_21": {},
                "is_over_65": {}
```

2024-01-06 02:10 UTC, selfissued commented
OK, I switched it back to using the ISO claim names.  If it were us creating new misleading claim names, I'd stand by my request for the change, but given we're copying misleading claim names created by ISO, I'll hold my nose and live with it.

2024-01-06 20:26 UTC, bc-pi approved these changes

2024-01-07 12:05 UTC, paulbastian approved these changes

2024-01-08 18:14 UTC, peppelinux approved these changes

2024-01-08 22:11 UTC, tplooker approved these changes

2024-01-10 07:12 UTC, Sakurann approved these changes

2024-01-10 07:14 UTC, merged

2024-01-10 07:14 UTC, Sakurann commented
@selfissued please make it clear in the original issue which of the taka's issues have been addressed.