Fix layout in "VC Secured using Data Integrity" issuer metadata
openid/OpenID4VCI pull request #232
Opened 2024-01-24 09:08 UTC by jogu

Indentation of 'mandatory' was incorrect making it appear at the wrong level in the bulleted list.

2024-01-24 14:40 UTC, tlodderstedt approved these changes

2024-01-24 18:09 UTC, c2bo approved these changes

2024-01-25 16:28 UTC, Sakurann requested changes
the current indentation is correct because `mandatory` is one of the parameters that  can be included inside `credentialSubject`.

2024-01-25 16:29 UTC, Sakurann approved these changes

2024-01-25 16:30 UTC, merged