Mnr changes
openid/OpenID4VCI pull request #253
Opened 2024-02-06 21:53 UTC by adeinega

A Credential Issuer URL shouldn not already include the query component per 11.2.2.

If an intent for the Wallet was to not add any query parameters for the Credential Issuer Identifier then this sentence should be changed to better reflect this.

2024-02-07 02:46 UTC, tplooker approved these changes
I agree with @adeinega, I believe the normative requirement that this PR removes is needless duplication

2024-02-07 16:59 UTC, Sakurann reviewed
if you are removing a normative statement, it is not an editorial change. please change the PR title accordingly

2024-02-08 15:39 UTC, pmhsfelix commented
Agree with the removal given both:
- the restriction that the issuer ID cannot have query string.
- the documented URI creation procedure for the metadata GET from the issuer ID.

2024-02-08 15:39 UTC, pmhsfelix approved these changes

2024-02-08 15:56 UTC, paulbastian requested changes
The existing query statement is only refering to the the [Credential Issuer Identifier](https://openid.github.io/OpenID4VCI/openid-4-verifiable-credential-issuance-wg-draft.html#name-credential-issuer-identifie).

I would propose to move this statement one paragraph earlier as:
"Credential Issuers publishing metadata MUST make a JSON document available at the path formed by concatenating the string /.well-known/openid-credential-issuer to the Credential Issuer Identifier. **The resulting URL SHOULD NOT contain any query parameters**"

2024-02-08 16:18 UTC, selfissued approved these changes

2024-02-08 16:21 UTC, paulbastian approved these changes
agreed afet wg call

2024-02-08 16:37 UTC, merged