chore: added more examples illustrating the use of Authorization Servers (AS) and Resource Servers (RS) in this specification
openid/OpenID4VCI pull request #322
Opened 2024-05-16 20:57 UTC by peppelinux

this PR is merely editorial and aims to resolve the issue https://github.com/openid/OpenID4VCI/issues/311

2024-05-17 09:32 UTC, jogu approved these changes

2024-05-17 09:32 UTC, jogu commented on openid-4-verifiable-credential-issuance-1_0.md
> +:  An entity used by the Holder to request, receive, store, present, and manage Verifiable Credentials and cryptographic key material. There is no single deployment model of a Wallet: Credentials and
```suggestion
:  An entity used by the Holder to request, receive, store, present, and manage Verifiable Credentials and cryptographic key material. There is no single deployment model of a Wallet: Credentials and keys can be stored and managed either locally, through a remote self-hosted service, or via a remote third-party service. In the context of this specification, the Wallet acts as an OAuth 2.0 Client (see [@!RFC6749]) and obtains an Access Token to access an OAuth 2.0 Resource Server (Credential Endpoint).
```

2024-05-20 18:11 UTC, bc-pi approved these changes

2024-05-23 17:34 UTC, paulbastian approved these changes

2024-05-27 15:36 UTC, c2bo approved these changes

2024-05-27 19:44 UTC, Sakurann commented on openid-4-verifiable-credential-issuance-1_0.md
> +According to the OAuth 2.0 paradigm, each Credential Issuer acts as a Resource Server that is protected by an Access Token issued by an Authorization Server, as defined in OAuth 2.0 [@!RFC6749]. The
```suggestion
According to the OAuth 2.0 framework, each Credential Issuer acts as a Resource Server that is protected by an Access Token issued by an Authorization Server, as defined in OAuth 2.0 [@!RFC6749]. The same Authorization Server can protect one or more Credential Issuers. Wallets identify the Authorization Server for a Credential Issuer by referring to the Credential Issuer's metadata (see (#credential-issuer-metadata)).
```
let's not use lower-case may, and i think `framework` fits better than `paradigm`

2024-05-28 07:10 UTC, peppelinux commented on openid-4-verifiable-credential-issuance-1_0.md
>  ~~~ ascii-art
in this figure the CI is the first entity the wallet interacts with. In this example the discovery of the AS starts from the CI metadata

2024-05-29 18:42 UTC, jogu commented
Discussed on today's WG call:

1. There was a consensus that splitting the credential issuer & the AS in the diagrams is a good idea
2. However we felt that the credential issuer should be to the right of the authorization server, as in most oauth sequence diagrams the resource server is shown on the right hand side of the authorization server and it was felt it would help people's mental models if we followed that convention.
3. If we're going to add AS to this diagram, then we should add it to all diagrams (I think there's only one other diagram)

2024-05-29 18:43 UTC, jogu requested changes
as per my above comment

2024-05-30 09:42 UTC, peppelinux commented
I can do that during the next week, thank you for the feedback

2024-06-08 17:51 UTC, peppelinux commented on openid-4-verifiable-credential-issuance-1_0.md
> +    |                |<-----------------------------|                        |
```suggestion
+----------+   +-----------+            +----------------------+     +-------------------+
| End-User |   |   Wallet  |            | Authorization Server |     | Credential Issuer |
+----------+   +-----------+            +----------------------+     +-------------------+
    |                |                              |                        |
    | (1a) End-User  |                              |                        |
    |  selects       |  (1b) Credential Offer       |                        |
    |  Credential--->|  (credential type)           |                        |
    |                |<------------------------------------------------------|
    |                |                              |                        |
    |                |  (2) Obtains Issuer's        |                        |
    |                |      Credential Issuer       |                        |
    |                |      metadata                |                        |
    |                |------------------------------------------------------>|
    |                |                              |                        |
    |                |                              |  (3) Authorization     |
    |                |                              |      Request           |
    |                |                              |      (type(s) of       |
    |                |                              |      Credentials to    |
    |                |                              |      be issued)        |
    |                |----------------------------->|                        |
    |                |                              |                        |
    |  End-User Authentication / Consent            |                        |
    |                |                              |  (4) Authorization     |
    |                |                              |      Response (code)   |
    |                |<-----------------------------|                        |
    |                |                              |                        |
    |                |                              |  (5) Token Request     |
    |                |                              |      (code)            |
    |                |----------------------------->|      Token Response    |
    |                |                              |      (Access Token)    |
    |                |<-----------------------------|                        |
    |                |                              |                        |
    |                |  (6) Credential Request      |                        |
    |                |      (Access Token, proof(s))|                        |
    |                |------------------------------------------------------>|
    |                |                              |                        |
    |                |      Credential Response     |                        |
    |                |      with Credential(s) OR   |                        |
    |                |      Transaction ID          |                        |
    |                |<-----------------------------------------------------|
```

2024-06-08 17:52 UTC, peppelinux commented on openid-4-verifiable-credential-issuance-1_0.md
>  ~~~ ascii-art
done.

2024-06-08 17:58 UTC, peppelinux commented
@jogu I did the requested changes here: https://github.com/openid/OpenID4VCI/pull/322/commits/0521a835e0299be7d74937e33c8ecbaa6de2dcf4

2024-06-17 21:06 UTC, Sakurann approved these changes
thank you, Giuseppe!

2024-06-18 08:40 UTC, jogu approved these changes

2024-06-18 08:40 UTC, merged