IANA considerations for keyattestation+jwt
openid/OpenID4VCI pull request #439
Opened 2024-12-21 15:13 UTC by c2bo

Fixes #435

I just copied the other media types entry, adjusted some text and kept Torsten as author - hope that is fine @tlodderstedt ?

2025-01-07 19:34 UTC, paulbastian approved these changes

2025-02-06 14:10 UTC, Sakurann requested changes
key-attestaion+jwt is clearer

2025-02-06 14:10 UTC, Sakurann commented on openid-4-verifiable-credential-issuance-1_0.md
> +* Subtype name: `keyattestation+jwt`
```suggestion
* Subtype name: `key-attestation+jwt`
```

2025-02-06 15:37 UTC, bc-pi commented on openid-4-verifiable-credential-issuance-1_0.md
> +* Subtype name: `keyattestation+jwt`
would need to update the actual text and example(s) in the document too

2025-02-10 11:02 UTC, c2bo commented
Changed it from `keyattestation+jwt` to `key-attestation+jwt` in the media type registration and key attestation section

2025-02-10 21:54 UTC, Sakurann approved these changes

2025-02-10 22:38 UTC, bc-pi approved these changes

2025-02-10 23:00 UTC, selfissued approved these changes

2025-02-11 13:03 UTC, merged